/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AuthedLayoutRouteImport } from './routes/_authed/_layout'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedOnboardingAcademicSetupRouteImport } from './routes/_authed/onboarding/academic-setup'
import { Route as AuthedDashboardTeacherRouteImport } from './routes/_authed/dashboard/teacher'
import { Route as AuthedDashboardStudentRouteImport } from './routes/_authed/dashboard/student'
import { Route as AuthedDashboardPrincipalRouteImport } from './routes/_authed/dashboard/principal'
import { Route as AuthedDashboardAdminStaffRouteImport } from './routes/_authed/dashboard/admin-staff'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingAcademicSetupRoute =
  AuthedOnboardingAcademicSetupRouteImport.update({
    id: '/onboarding/academic-setup',
    path: '/onboarding/academic-setup',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardTeacherRoute = AuthedDashboardTeacherRouteImport.update({
  id: '/dashboard/teacher',
  path: '/dashboard/teacher',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardStudentRoute = AuthedDashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardPrincipalRoute =
  AuthedDashboardPrincipalRouteImport.update({
    id: '/dashboard/principal',
    path: '/dashboard/principal',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardAdminStaffRoute =
  AuthedDashboardAdminStaffRouteImport.update({
    id: '/dashboard/admin-staff',
    path: '/dashboard/admin-staff',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/dashboard/admin-staff': typeof AuthedDashboardAdminStaffRoute
  '/dashboard/principal': typeof AuthedDashboardPrincipalRoute
  '/dashboard/student': typeof AuthedDashboardStudentRoute
  '/dashboard/teacher': typeof AuthedDashboardTeacherRoute
  '/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/dashboard/admin-staff': typeof AuthedDashboardAdminStaffRoute
  '/dashboard/principal': typeof AuthedDashboardPrincipalRoute
  '/dashboard/student': typeof AuthedDashboardStudentRoute
  '/dashboard/teacher': typeof AuthedDashboardTeacherRoute
  '/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_layout': typeof AuthedLayoutRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/dashboard/admin-staff': typeof AuthedDashboardAdminStaffRoute
  '/_authed/dashboard/principal': typeof AuthedDashboardPrincipalRoute
  '/_authed/dashboard/student': typeof AuthedDashboardStudentRoute
  '/_authed/dashboard/teacher': typeof AuthedDashboardTeacherRoute
  '/_authed/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/dashboard/admin-staff'
    | '/dashboard/principal'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/onboarding/academic-setup'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/dashboard/admin-staff'
    | '/dashboard/principal'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/onboarding/academic-setup'
    | '/dashboard'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/_layout'
    | '/auth/_layout'
    | '/auth/login'
    | '/auth/register'
    | '/_authed/'
    | '/_authed/dashboard/admin-staff'
    | '/_authed/dashboard/principal'
    | '/_authed/dashboard/student'
    | '/_authed/dashboard/teacher'
    | '/_authed/onboarding/academic-setup'
    | '/_authed/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_layout': {
      id: '/_authed/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/academic-setup': {
      id: '/_authed/onboarding/academic-setup'
      path: '/onboarding/academic-setup'
      fullPath: '/onboarding/academic-setup'
      preLoaderRoute: typeof AuthedOnboardingAcademicSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/teacher': {
      id: '/_authed/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof AuthedDashboardTeacherRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/student': {
      id: '/_authed/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthedDashboardStudentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/principal': {
      id: '/_authed/dashboard/principal'
      path: '/dashboard/principal'
      fullPath: '/dashboard/principal'
      preLoaderRoute: typeof AuthedDashboardPrincipalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/admin-staff': {
      id: '/_authed/dashboard/admin-staff'
      path: '/dashboard/admin-staff'
      fullPath: '/dashboard/admin-staff'
      preLoaderRoute: typeof AuthedDashboardAdminStaffRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedLayoutRoute: typeof AuthedLayoutRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDashboardAdminStaffRoute: typeof AuthedDashboardAdminStaffRoute
  AuthedDashboardPrincipalRoute: typeof AuthedDashboardPrincipalRoute
  AuthedDashboardStudentRoute: typeof AuthedDashboardStudentRoute
  AuthedDashboardTeacherRoute: typeof AuthedDashboardTeacherRoute
  AuthedOnboardingAcademicSetupRoute: typeof AuthedOnboardingAcademicSetupRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLayoutRoute: AuthedLayoutRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDashboardAdminStaffRoute: AuthedDashboardAdminStaffRoute,
  AuthedDashboardPrincipalRoute: AuthedDashboardPrincipalRoute,
  AuthedDashboardStudentRoute: AuthedDashboardStudentRoute,
  AuthedDashboardTeacherRoute: AuthedDashboardTeacherRoute,
  AuthedOnboardingAcademicSetupRoute: AuthedOnboardingAcademicSetupRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
