/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth/accept-invite'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AuthedLayoutRouteImport } from './routes/_authed/_layout'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedOnboardingAcademicSetupRouteImport } from './routes/_authed/onboarding/academic-setup'
import { Route as AuthedDashboardTopnavsRouteImport } from './routes/_authed/dashboard/_topnavs'
import { Route as AuthedDashboardSidenavsRouteImport } from './routes/_authed/dashboard/_sidenavs'
import { Route as AuthedDashboardTopnavsPrincipalRouteImport } from './routes/_authed/dashboard/_topnavs/principal'
import { Route as AuthedDashboardSidenavsAdminStaffRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff'
import { Route as AuthedDashboardTopnavsTeacherIndexRouteImport } from './routes/_authed/dashboard/_topnavs/teacher/index'
import { Route as AuthedDashboardTopnavsStudentIndexRouteImport } from './routes/_authed/dashboard/_topnavs/student/index'
import { Route as AuthedDashboardSidenavsAdminStaffIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/index'
import { Route as AuthedDashboardSidenavsAdminStaffAcademicPeriodsRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/academic-periods'
import { Route as AuthedDashboardTopnavsTeacherScheduleIndexRouteImport } from './routes/_authed/dashboard/_topnavs/teacher/schedule/index'
import { Route as AuthedDashboardTopnavsTeacherRecapIndexRouteImport } from './routes/_authed/dashboard/_topnavs/teacher/recap/index'
import { Route as AuthedDashboardTopnavsTeacherCompileIndexRouteImport } from './routes/_authed/dashboard/_topnavs/teacher/compile/index'
import { Route as AuthedDashboardTopnavsTeacherAssessmentsIndexRouteImport } from './routes/_authed/dashboard/_topnavs/teacher/assessments/index'
import { Route as AuthedDashboardTopnavsStudentScheduleIndexRouteImport } from './routes/_authed/dashboard/_topnavs/student/schedule/index'
import { Route as AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/teaching-assignments/index'
import { Route as AuthedDashboardSidenavsAdminStaffTeachersIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/teachers/index'
import { Route as AuthedDashboardSidenavsAdminStaffSubjectsIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/subjects/index'
import { Route as AuthedDashboardSidenavsAdminStaffStudentsIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/students/index'
import { Route as AuthedDashboardSidenavsAdminStaffSettingsIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/settings/index'
import { Route as AuthedDashboardSidenavsAdminStaffSessionsIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/sessions/index'
import { Route as AuthedDashboardSidenavsAdminStaffGroupsIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/groups/index'
import { Route as AuthedDashboardSidenavsAdminStaffClassesIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/classes/index'
import { Route as AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/academic-years/index'
import { Route as AuthedDashboardTopnavsTeacherSessionsSessionIdRouteImport } from './routes/_authed/dashboard/_topnavs/teacher/sessions/$sessionId'
import { Route as AuthedDashboardSidenavsAdminStaffStudentsImportRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/students/import'
import { Route as AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/settings/customization/index'
import { Route as AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRouteImport } from './routes/_authed/dashboard/_topnavs/teacher/assessments/scores/$componentId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingAcademicSetupRoute =
  AuthedOnboardingAcademicSetupRouteImport.update({
    id: '/onboarding/academic-setup',
    path: '/onboarding/academic-setup',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardTopnavsRoute = AuthedDashboardTopnavsRouteImport.update({
  id: '/dashboard/_topnavs',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardSidenavsRoute = AuthedDashboardSidenavsRouteImport.update({
  id: '/dashboard/_sidenavs',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardTopnavsPrincipalRoute =
  AuthedDashboardTopnavsPrincipalRouteImport.update({
    id: '/principal',
    path: '/principal',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffRoute =
  AuthedDashboardSidenavsAdminStaffRouteImport.update({
    id: '/admin-staff',
    path: '/admin-staff',
    getParentRoute: () => AuthedDashboardSidenavsRoute,
  } as any)
const AuthedDashboardTopnavsTeacherIndexRoute =
  AuthedDashboardTopnavsTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardTopnavsStudentIndexRoute =
  AuthedDashboardTopnavsStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffIndexRoute =
  AuthedDashboardSidenavsAdminStaffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute =
  AuthedDashboardSidenavsAdminStaffAcademicPeriodsRouteImport.update({
    id: '/academic-periods',
    path: '/academic-periods',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardTopnavsTeacherScheduleIndexRoute =
  AuthedDashboardTopnavsTeacherScheduleIndexRouteImport.update({
    id: '/teacher/schedule/',
    path: '/teacher/schedule/',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardTopnavsTeacherRecapIndexRoute =
  AuthedDashboardTopnavsTeacherRecapIndexRouteImport.update({
    id: '/teacher/recap/',
    path: '/teacher/recap/',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardTopnavsTeacherCompileIndexRoute =
  AuthedDashboardTopnavsTeacherCompileIndexRouteImport.update({
    id: '/teacher/compile/',
    path: '/teacher/compile/',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardTopnavsTeacherAssessmentsIndexRoute =
  AuthedDashboardTopnavsTeacherAssessmentsIndexRouteImport.update({
    id: '/teacher/assessments/',
    path: '/teacher/assessments/',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardTopnavsStudentScheduleIndexRoute =
  AuthedDashboardTopnavsStudentScheduleIndexRouteImport.update({
    id: '/student/schedule/',
    path: '/student/schedule/',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute =
  AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRouteImport.update({
    id: '/teaching-assignments/',
    path: '/teaching-assignments/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffTeachersIndexRoute =
  AuthedDashboardSidenavsAdminStaffTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute =
  AuthedDashboardSidenavsAdminStaffSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffStudentsIndexRoute =
  AuthedDashboardSidenavsAdminStaffStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffSettingsIndexRoute =
  AuthedDashboardSidenavsAdminStaffSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffSessionsIndexRoute =
  AuthedDashboardSidenavsAdminStaffSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffGroupsIndexRoute =
  AuthedDashboardSidenavsAdminStaffGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffClassesIndexRoute =
  AuthedDashboardSidenavsAdminStaffClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute =
  AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRouteImport.update({
    id: '/academic-years/',
    path: '/academic-years/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardTopnavsTeacherSessionsSessionIdRoute =
  AuthedDashboardTopnavsTeacherSessionsSessionIdRouteImport.update({
    id: '/teacher/sessions/$sessionId',
    path: '/teacher/sessions/$sessionId',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffStudentsImportRoute =
  AuthedDashboardSidenavsAdminStaffStudentsImportRouteImport.update({
    id: '/students/import',
    path: '/students/import',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute =
  AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRouteImport.update(
    {
      id: '/settings/customization/',
      path: '/settings/customization/',
      getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
    } as any,
  )
const AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute =
  AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRouteImport.update({
    id: '/teacher/assessments/scores/$componentId',
    path: '/teacher/assessments/scores/$componentId',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/dashboard/admin-staff': typeof AuthedDashboardSidenavsAdminStaffRouteWithChildren
  '/dashboard/principal': typeof AuthedDashboardTopnavsPrincipalRoute
  '/dashboard/admin-staff/academic-periods': typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  '/dashboard/admin-staff/': typeof AuthedDashboardSidenavsAdminStaffIndexRoute
  '/dashboard/student': typeof AuthedDashboardTopnavsStudentIndexRoute
  '/dashboard/teacher': typeof AuthedDashboardTopnavsTeacherIndexRoute
  '/dashboard/admin-staff/students/import': typeof AuthedDashboardSidenavsAdminStaffStudentsImportRoute
  '/dashboard/teacher/sessions/$sessionId': typeof AuthedDashboardTopnavsTeacherSessionsSessionIdRoute
  '/dashboard/admin-staff/academic-years': typeof AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute
  '/dashboard/admin-staff/classes': typeof AuthedDashboardSidenavsAdminStaffClassesIndexRoute
  '/dashboard/admin-staff/groups': typeof AuthedDashboardSidenavsAdminStaffGroupsIndexRoute
  '/dashboard/admin-staff/sessions': typeof AuthedDashboardSidenavsAdminStaffSessionsIndexRoute
  '/dashboard/admin-staff/settings': typeof AuthedDashboardSidenavsAdminStaffSettingsIndexRoute
  '/dashboard/admin-staff/students': typeof AuthedDashboardSidenavsAdminStaffStudentsIndexRoute
  '/dashboard/admin-staff/subjects': typeof AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute
  '/dashboard/admin-staff/teachers': typeof AuthedDashboardSidenavsAdminStaffTeachersIndexRoute
  '/dashboard/admin-staff/teaching-assignments': typeof AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute
  '/dashboard/student/schedule': typeof AuthedDashboardTopnavsStudentScheduleIndexRoute
  '/dashboard/teacher/assessments': typeof AuthedDashboardTopnavsTeacherAssessmentsIndexRoute
  '/dashboard/teacher/compile': typeof AuthedDashboardTopnavsTeacherCompileIndexRoute
  '/dashboard/teacher/recap': typeof AuthedDashboardTopnavsTeacherRecapIndexRoute
  '/dashboard/teacher/schedule': typeof AuthedDashboardTopnavsTeacherScheduleIndexRoute
  '/dashboard/teacher/assessments/scores/$componentId': typeof AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute
  '/dashboard/admin-staff/settings/customization': typeof AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/dashboard/principal': typeof AuthedDashboardTopnavsPrincipalRoute
  '/dashboard/admin-staff/academic-periods': typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  '/dashboard/admin-staff': typeof AuthedDashboardSidenavsAdminStaffIndexRoute
  '/dashboard/student': typeof AuthedDashboardTopnavsStudentIndexRoute
  '/dashboard/teacher': typeof AuthedDashboardTopnavsTeacherIndexRoute
  '/dashboard/admin-staff/students/import': typeof AuthedDashboardSidenavsAdminStaffStudentsImportRoute
  '/dashboard/teacher/sessions/$sessionId': typeof AuthedDashboardTopnavsTeacherSessionsSessionIdRoute
  '/dashboard/admin-staff/academic-years': typeof AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute
  '/dashboard/admin-staff/classes': typeof AuthedDashboardSidenavsAdminStaffClassesIndexRoute
  '/dashboard/admin-staff/groups': typeof AuthedDashboardSidenavsAdminStaffGroupsIndexRoute
  '/dashboard/admin-staff/sessions': typeof AuthedDashboardSidenavsAdminStaffSessionsIndexRoute
  '/dashboard/admin-staff/settings': typeof AuthedDashboardSidenavsAdminStaffSettingsIndexRoute
  '/dashboard/admin-staff/students': typeof AuthedDashboardSidenavsAdminStaffStudentsIndexRoute
  '/dashboard/admin-staff/subjects': typeof AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute
  '/dashboard/admin-staff/teachers': typeof AuthedDashboardSidenavsAdminStaffTeachersIndexRoute
  '/dashboard/admin-staff/teaching-assignments': typeof AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute
  '/dashboard/student/schedule': typeof AuthedDashboardTopnavsStudentScheduleIndexRoute
  '/dashboard/teacher/assessments': typeof AuthedDashboardTopnavsTeacherAssessmentsIndexRoute
  '/dashboard/teacher/compile': typeof AuthedDashboardTopnavsTeacherCompileIndexRoute
  '/dashboard/teacher/recap': typeof AuthedDashboardTopnavsTeacherRecapIndexRoute
  '/dashboard/teacher/schedule': typeof AuthedDashboardTopnavsTeacherScheduleIndexRoute
  '/dashboard/teacher/assessments/scores/$componentId': typeof AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute
  '/dashboard/admin-staff/settings/customization': typeof AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_layout': typeof AuthedLayoutRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/dashboard/_sidenavs': typeof AuthedDashboardSidenavsRouteWithChildren
  '/_authed/dashboard/_topnavs': typeof AuthedDashboardTopnavsRouteWithChildren
  '/_authed/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff': typeof AuthedDashboardSidenavsAdminStaffRouteWithChildren
  '/_authed/dashboard/_topnavs/principal': typeof AuthedDashboardTopnavsPrincipalRoute
  '/_authed/dashboard/_sidenavs/admin-staff/academic-periods': typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  '/_authed/dashboard/_sidenavs/admin-staff/': typeof AuthedDashboardSidenavsAdminStaffIndexRoute
  '/_authed/dashboard/_topnavs/student/': typeof AuthedDashboardTopnavsStudentIndexRoute
  '/_authed/dashboard/_topnavs/teacher/': typeof AuthedDashboardTopnavsTeacherIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/students/import': typeof AuthedDashboardSidenavsAdminStaffStudentsImportRoute
  '/_authed/dashboard/_topnavs/teacher/sessions/$sessionId': typeof AuthedDashboardTopnavsTeacherSessionsSessionIdRoute
  '/_authed/dashboard/_sidenavs/admin-staff/academic-years/': typeof AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/classes/': typeof AuthedDashboardSidenavsAdminStaffClassesIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/groups/': typeof AuthedDashboardSidenavsAdminStaffGroupsIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/sessions/': typeof AuthedDashboardSidenavsAdminStaffSessionsIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/settings/': typeof AuthedDashboardSidenavsAdminStaffSettingsIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/students/': typeof AuthedDashboardSidenavsAdminStaffStudentsIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/subjects/': typeof AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/teachers/': typeof AuthedDashboardSidenavsAdminStaffTeachersIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff/teaching-assignments/': typeof AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute
  '/_authed/dashboard/_topnavs/student/schedule/': typeof AuthedDashboardTopnavsStudentScheduleIndexRoute
  '/_authed/dashboard/_topnavs/teacher/assessments/': typeof AuthedDashboardTopnavsTeacherAssessmentsIndexRoute
  '/_authed/dashboard/_topnavs/teacher/compile/': typeof AuthedDashboardTopnavsTeacherCompileIndexRoute
  '/_authed/dashboard/_topnavs/teacher/recap/': typeof AuthedDashboardTopnavsTeacherRecapIndexRoute
  '/_authed/dashboard/_topnavs/teacher/schedule/': typeof AuthedDashboardTopnavsTeacherScheduleIndexRoute
  '/_authed/dashboard/_topnavs/teacher/assessments/scores/$componentId': typeof AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute
  '/_authed/dashboard/_sidenavs/admin-staff/settings/customization/': typeof AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/accept-invite'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/dashboard'
    | '/onboarding/academic-setup'
    | '/dashboard/admin-staff'
    | '/dashboard/principal'
    | '/dashboard/admin-staff/academic-periods'
    | '/dashboard/admin-staff/'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/admin-staff/students/import'
    | '/dashboard/teacher/sessions/$sessionId'
    | '/dashboard/admin-staff/academic-years'
    | '/dashboard/admin-staff/classes'
    | '/dashboard/admin-staff/groups'
    | '/dashboard/admin-staff/sessions'
    | '/dashboard/admin-staff/settings'
    | '/dashboard/admin-staff/students'
    | '/dashboard/admin-staff/subjects'
    | '/dashboard/admin-staff/teachers'
    | '/dashboard/admin-staff/teaching-assignments'
    | '/dashboard/student/schedule'
    | '/dashboard/teacher/assessments'
    | '/dashboard/teacher/compile'
    | '/dashboard/teacher/recap'
    | '/dashboard/teacher/schedule'
    | '/dashboard/teacher/assessments/scores/$componentId'
    | '/dashboard/admin-staff/settings/customization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/accept-invite'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/dashboard'
    | '/onboarding/academic-setup'
    | '/dashboard/principal'
    | '/dashboard/admin-staff/academic-periods'
    | '/dashboard/admin-staff'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/admin-staff/students/import'
    | '/dashboard/teacher/sessions/$sessionId'
    | '/dashboard/admin-staff/academic-years'
    | '/dashboard/admin-staff/classes'
    | '/dashboard/admin-staff/groups'
    | '/dashboard/admin-staff/sessions'
    | '/dashboard/admin-staff/settings'
    | '/dashboard/admin-staff/students'
    | '/dashboard/admin-staff/subjects'
    | '/dashboard/admin-staff/teachers'
    | '/dashboard/admin-staff/teaching-assignments'
    | '/dashboard/student/schedule'
    | '/dashboard/teacher/assessments'
    | '/dashboard/teacher/compile'
    | '/dashboard/teacher/recap'
    | '/dashboard/teacher/schedule'
    | '/dashboard/teacher/assessments/scores/$componentId'
    | '/dashboard/admin-staff/settings/customization'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/_layout'
    | '/auth/_layout'
    | '/auth/accept-invite'
    | '/auth/login'
    | '/auth/register'
    | '/_authed/'
    | '/_authed/dashboard/_sidenavs'
    | '/_authed/dashboard/_topnavs'
    | '/_authed/onboarding/academic-setup'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/_sidenavs/admin-staff'
    | '/_authed/dashboard/_topnavs/principal'
    | '/_authed/dashboard/_sidenavs/admin-staff/academic-periods'
    | '/_authed/dashboard/_sidenavs/admin-staff/'
    | '/_authed/dashboard/_topnavs/student/'
    | '/_authed/dashboard/_topnavs/teacher/'
    | '/_authed/dashboard/_sidenavs/admin-staff/students/import'
    | '/_authed/dashboard/_topnavs/teacher/sessions/$sessionId'
    | '/_authed/dashboard/_sidenavs/admin-staff/academic-years/'
    | '/_authed/dashboard/_sidenavs/admin-staff/classes/'
    | '/_authed/dashboard/_sidenavs/admin-staff/groups/'
    | '/_authed/dashboard/_sidenavs/admin-staff/sessions/'
    | '/_authed/dashboard/_sidenavs/admin-staff/settings/'
    | '/_authed/dashboard/_sidenavs/admin-staff/students/'
    | '/_authed/dashboard/_sidenavs/admin-staff/subjects/'
    | '/_authed/dashboard/_sidenavs/admin-staff/teachers/'
    | '/_authed/dashboard/_sidenavs/admin-staff/teaching-assignments/'
    | '/_authed/dashboard/_topnavs/student/schedule/'
    | '/_authed/dashboard/_topnavs/teacher/assessments/'
    | '/_authed/dashboard/_topnavs/teacher/compile/'
    | '/_authed/dashboard/_topnavs/teacher/recap/'
    | '/_authed/dashboard/_topnavs/teacher/schedule/'
    | '/_authed/dashboard/_topnavs/teacher/assessments/scores/$componentId'
    | '/_authed/dashboard/_sidenavs/admin-staff/settings/customization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_layout': {
      id: '/_authed/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/academic-setup': {
      id: '/_authed/onboarding/academic-setup'
      path: '/onboarding/academic-setup'
      fullPath: '/onboarding/academic-setup'
      preLoaderRoute: typeof AuthedOnboardingAcademicSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/_topnavs': {
      id: '/_authed/dashboard/_topnavs'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardTopnavsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/_sidenavs': {
      id: '/_authed/dashboard/_sidenavs'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardSidenavsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/_topnavs/principal': {
      id: '/_authed/dashboard/_topnavs/principal'
      path: '/principal'
      fullPath: '/dashboard/principal'
      preLoaderRoute: typeof AuthedDashboardTopnavsPrincipalRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff': {
      id: '/_authed/dashboard/_sidenavs/admin-staff'
      path: '/admin-staff'
      fullPath: '/dashboard/admin-staff'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffRouteImport
      parentRoute: typeof AuthedDashboardSidenavsRoute
    }
    '/_authed/dashboard/_topnavs/teacher/': {
      id: '/_authed/dashboard/_topnavs/teacher/'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherIndexRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_topnavs/student/': {
      id: '/_authed/dashboard/_topnavs/student/'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthedDashboardTopnavsStudentIndexRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/'
      path: '/'
      fullPath: '/dashboard/admin-staff/'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/academic-periods': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/academic-periods'
      path: '/academic-periods'
      fullPath: '/dashboard/admin-staff/academic-periods'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_topnavs/teacher/schedule/': {
      id: '/_authed/dashboard/_topnavs/teacher/schedule/'
      path: '/teacher/schedule'
      fullPath: '/dashboard/teacher/schedule'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherScheduleIndexRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_topnavs/teacher/recap/': {
      id: '/_authed/dashboard/_topnavs/teacher/recap/'
      path: '/teacher/recap'
      fullPath: '/dashboard/teacher/recap'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherRecapIndexRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_topnavs/teacher/compile/': {
      id: '/_authed/dashboard/_topnavs/teacher/compile/'
      path: '/teacher/compile'
      fullPath: '/dashboard/teacher/compile'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherCompileIndexRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_topnavs/teacher/assessments/': {
      id: '/_authed/dashboard/_topnavs/teacher/assessments/'
      path: '/teacher/assessments'
      fullPath: '/dashboard/teacher/assessments'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherAssessmentsIndexRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_topnavs/student/schedule/': {
      id: '/_authed/dashboard/_topnavs/student/schedule/'
      path: '/student/schedule'
      fullPath: '/dashboard/student/schedule'
      preLoaderRoute: typeof AuthedDashboardTopnavsStudentScheduleIndexRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/teaching-assignments/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/teaching-assignments/'
      path: '/teaching-assignments'
      fullPath: '/dashboard/admin-staff/teaching-assignments'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/teachers/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/teachers/'
      path: '/teachers'
      fullPath: '/dashboard/admin-staff/teachers'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffTeachersIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/subjects/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/subjects/'
      path: '/subjects'
      fullPath: '/dashboard/admin-staff/subjects'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffSubjectsIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/students/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/students/'
      path: '/students'
      fullPath: '/dashboard/admin-staff/students'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffStudentsIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/settings/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/settings/'
      path: '/settings'
      fullPath: '/dashboard/admin-staff/settings'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffSettingsIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/sessions/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/admin-staff/sessions'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffSessionsIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/groups/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/groups/'
      path: '/groups'
      fullPath: '/dashboard/admin-staff/groups'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffGroupsIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/classes/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/classes/'
      path: '/classes'
      fullPath: '/dashboard/admin-staff/classes'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffClassesIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/academic-years/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/academic-years/'
      path: '/academic-years'
      fullPath: '/dashboard/admin-staff/academic-years'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_topnavs/teacher/sessions/$sessionId': {
      id: '/_authed/dashboard/_topnavs/teacher/sessions/$sessionId'
      path: '/teacher/sessions/$sessionId'
      fullPath: '/dashboard/teacher/sessions/$sessionId'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherSessionsSessionIdRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/students/import': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/students/import'
      path: '/students/import'
      fullPath: '/dashboard/admin-staff/students/import'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffStudentsImportRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/settings/customization/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/settings/customization/'
      path: '/settings/customization'
      fullPath: '/dashboard/admin-staff/settings/customization'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_topnavs/teacher/assessments/scores/$componentId': {
      id: '/_authed/dashboard/_topnavs/teacher/assessments/scores/$componentId'
      path: '/teacher/assessments/scores/$componentId'
      fullPath: '/dashboard/teacher/assessments/scores/$componentId'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
  }
}

interface AuthedDashboardSidenavsAdminStaffRouteChildren {
  AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  AuthedDashboardSidenavsAdminStaffIndexRoute: typeof AuthedDashboardSidenavsAdminStaffIndexRoute
  AuthedDashboardSidenavsAdminStaffStudentsImportRoute: typeof AuthedDashboardSidenavsAdminStaffStudentsImportRoute
  AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute
  AuthedDashboardSidenavsAdminStaffClassesIndexRoute: typeof AuthedDashboardSidenavsAdminStaffClassesIndexRoute
  AuthedDashboardSidenavsAdminStaffGroupsIndexRoute: typeof AuthedDashboardSidenavsAdminStaffGroupsIndexRoute
  AuthedDashboardSidenavsAdminStaffSessionsIndexRoute: typeof AuthedDashboardSidenavsAdminStaffSessionsIndexRoute
  AuthedDashboardSidenavsAdminStaffSettingsIndexRoute: typeof AuthedDashboardSidenavsAdminStaffSettingsIndexRoute
  AuthedDashboardSidenavsAdminStaffStudentsIndexRoute: typeof AuthedDashboardSidenavsAdminStaffStudentsIndexRoute
  AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute: typeof AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute
  AuthedDashboardSidenavsAdminStaffTeachersIndexRoute: typeof AuthedDashboardSidenavsAdminStaffTeachersIndexRoute
  AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute: typeof AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute
  AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute: typeof AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute
}

const AuthedDashboardSidenavsAdminStaffRouteChildren: AuthedDashboardSidenavsAdminStaffRouteChildren =
  {
    AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute:
      AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute,
    AuthedDashboardSidenavsAdminStaffIndexRoute:
      AuthedDashboardSidenavsAdminStaffIndexRoute,
    AuthedDashboardSidenavsAdminStaffStudentsImportRoute:
      AuthedDashboardSidenavsAdminStaffStudentsImportRoute,
    AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute:
      AuthedDashboardSidenavsAdminStaffAcademicYearsIndexRoute,
    AuthedDashboardSidenavsAdminStaffClassesIndexRoute:
      AuthedDashboardSidenavsAdminStaffClassesIndexRoute,
    AuthedDashboardSidenavsAdminStaffGroupsIndexRoute:
      AuthedDashboardSidenavsAdminStaffGroupsIndexRoute,
    AuthedDashboardSidenavsAdminStaffSessionsIndexRoute:
      AuthedDashboardSidenavsAdminStaffSessionsIndexRoute,
    AuthedDashboardSidenavsAdminStaffSettingsIndexRoute:
      AuthedDashboardSidenavsAdminStaffSettingsIndexRoute,
    AuthedDashboardSidenavsAdminStaffStudentsIndexRoute:
      AuthedDashboardSidenavsAdminStaffStudentsIndexRoute,
    AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute:
      AuthedDashboardSidenavsAdminStaffSubjectsIndexRoute,
    AuthedDashboardSidenavsAdminStaffTeachersIndexRoute:
      AuthedDashboardSidenavsAdminStaffTeachersIndexRoute,
    AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute:
      AuthedDashboardSidenavsAdminStaffTeachingAssignmentsIndexRoute,
    AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute:
      AuthedDashboardSidenavsAdminStaffSettingsCustomizationIndexRoute,
  }

const AuthedDashboardSidenavsAdminStaffRouteWithChildren =
  AuthedDashboardSidenavsAdminStaffRoute._addFileChildren(
    AuthedDashboardSidenavsAdminStaffRouteChildren,
  )

interface AuthedDashboardSidenavsRouteChildren {
  AuthedDashboardSidenavsAdminStaffRoute: typeof AuthedDashboardSidenavsAdminStaffRouteWithChildren
}

const AuthedDashboardSidenavsRouteChildren: AuthedDashboardSidenavsRouteChildren =
  {
    AuthedDashboardSidenavsAdminStaffRoute:
      AuthedDashboardSidenavsAdminStaffRouteWithChildren,
  }

const AuthedDashboardSidenavsRouteWithChildren =
  AuthedDashboardSidenavsRoute._addFileChildren(
    AuthedDashboardSidenavsRouteChildren,
  )

interface AuthedDashboardTopnavsRouteChildren {
  AuthedDashboardTopnavsPrincipalRoute: typeof AuthedDashboardTopnavsPrincipalRoute
  AuthedDashboardTopnavsStudentIndexRoute: typeof AuthedDashboardTopnavsStudentIndexRoute
  AuthedDashboardTopnavsTeacherIndexRoute: typeof AuthedDashboardTopnavsTeacherIndexRoute
  AuthedDashboardTopnavsTeacherSessionsSessionIdRoute: typeof AuthedDashboardTopnavsTeacherSessionsSessionIdRoute
  AuthedDashboardTopnavsStudentScheduleIndexRoute: typeof AuthedDashboardTopnavsStudentScheduleIndexRoute
  AuthedDashboardTopnavsTeacherAssessmentsIndexRoute: typeof AuthedDashboardTopnavsTeacherAssessmentsIndexRoute
  AuthedDashboardTopnavsTeacherCompileIndexRoute: typeof AuthedDashboardTopnavsTeacherCompileIndexRoute
  AuthedDashboardTopnavsTeacherRecapIndexRoute: typeof AuthedDashboardTopnavsTeacherRecapIndexRoute
  AuthedDashboardTopnavsTeacherScheduleIndexRoute: typeof AuthedDashboardTopnavsTeacherScheduleIndexRoute
  AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute: typeof AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute
}

const AuthedDashboardTopnavsRouteChildren: AuthedDashboardTopnavsRouteChildren =
  {
    AuthedDashboardTopnavsPrincipalRoute: AuthedDashboardTopnavsPrincipalRoute,
    AuthedDashboardTopnavsStudentIndexRoute:
      AuthedDashboardTopnavsStudentIndexRoute,
    AuthedDashboardTopnavsTeacherIndexRoute:
      AuthedDashboardTopnavsTeacherIndexRoute,
    AuthedDashboardTopnavsTeacherSessionsSessionIdRoute:
      AuthedDashboardTopnavsTeacherSessionsSessionIdRoute,
    AuthedDashboardTopnavsStudentScheduleIndexRoute:
      AuthedDashboardTopnavsStudentScheduleIndexRoute,
    AuthedDashboardTopnavsTeacherAssessmentsIndexRoute:
      AuthedDashboardTopnavsTeacherAssessmentsIndexRoute,
    AuthedDashboardTopnavsTeacherCompileIndexRoute:
      AuthedDashboardTopnavsTeacherCompileIndexRoute,
    AuthedDashboardTopnavsTeacherRecapIndexRoute:
      AuthedDashboardTopnavsTeacherRecapIndexRoute,
    AuthedDashboardTopnavsTeacherScheduleIndexRoute:
      AuthedDashboardTopnavsTeacherScheduleIndexRoute,
    AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute:
      AuthedDashboardTopnavsTeacherAssessmentsScoresComponentIdRoute,
  }

const AuthedDashboardTopnavsRouteWithChildren =
  AuthedDashboardTopnavsRoute._addFileChildren(
    AuthedDashboardTopnavsRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedLayoutRoute: typeof AuthedLayoutRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDashboardSidenavsRoute: typeof AuthedDashboardSidenavsRouteWithChildren
  AuthedDashboardTopnavsRoute: typeof AuthedDashboardTopnavsRouteWithChildren
  AuthedOnboardingAcademicSetupRoute: typeof AuthedOnboardingAcademicSetupRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLayoutRoute: AuthedLayoutRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDashboardSidenavsRoute: AuthedDashboardSidenavsRouteWithChildren,
  AuthedDashboardTopnavsRoute: AuthedDashboardTopnavsRouteWithChildren,
  AuthedOnboardingAcademicSetupRoute: AuthedOnboardingAcademicSetupRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
