/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AuthedLayoutRouteImport } from './routes/_authed/_layout'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedOnboardingAcademicSetupRouteImport } from './routes/_authed/onboarding/academic-setup'
import { Route as AuthedDashboardTopnavsRouteImport } from './routes/_authed/dashboard/_topnavs'
import { Route as AuthedDashboardSidenavsRouteImport } from './routes/_authed/dashboard/_sidenavs'
import { Route as AuthedDashboardTopnavsTeacherRouteImport } from './routes/_authed/dashboard/_topnavs/teacher'
import { Route as AuthedDashboardTopnavsStudentRouteImport } from './routes/_authed/dashboard/_topnavs/student'
import { Route as AuthedDashboardTopnavsPrincipalRouteImport } from './routes/_authed/dashboard/_topnavs/principal'
import { Route as AuthedDashboardSidenavsAdminStaffRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff'
import { Route as AuthedDashboardSidenavsAdminStaffIndexRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/index'
import { Route as AuthedDashboardSidenavsAdminStaffAcademicYearsRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/academic-years'
import { Route as AuthedDashboardSidenavsAdminStaffAcademicPeriodsRouteImport } from './routes/_authed/dashboard/_sidenavs/admin-staff/academic-periods'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingAcademicSetupRoute =
  AuthedOnboardingAcademicSetupRouteImport.update({
    id: '/onboarding/academic-setup',
    path: '/onboarding/academic-setup',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardTopnavsRoute = AuthedDashboardTopnavsRouteImport.update({
  id: '/dashboard/_topnavs',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardSidenavsRoute = AuthedDashboardSidenavsRouteImport.update({
  id: '/dashboard/_sidenavs',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardTopnavsTeacherRoute =
  AuthedDashboardTopnavsTeacherRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardTopnavsStudentRoute =
  AuthedDashboardTopnavsStudentRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardTopnavsPrincipalRoute =
  AuthedDashboardTopnavsPrincipalRouteImport.update({
    id: '/principal',
    path: '/principal',
    getParentRoute: () => AuthedDashboardTopnavsRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffRoute =
  AuthedDashboardSidenavsAdminStaffRouteImport.update({
    id: '/admin-staff',
    path: '/admin-staff',
    getParentRoute: () => AuthedDashboardSidenavsRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffIndexRoute =
  AuthedDashboardSidenavsAdminStaffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffAcademicYearsRoute =
  AuthedDashboardSidenavsAdminStaffAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)
const AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute =
  AuthedDashboardSidenavsAdminStaffAcademicPeriodsRouteImport.update({
    id: '/academic-periods',
    path: '/academic-periods',
    getParentRoute: () => AuthedDashboardSidenavsAdminStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/dashboard/admin-staff': typeof AuthedDashboardSidenavsAdminStaffRouteWithChildren
  '/dashboard/principal': typeof AuthedDashboardTopnavsPrincipalRoute
  '/dashboard/student': typeof AuthedDashboardTopnavsStudentRoute
  '/dashboard/teacher': typeof AuthedDashboardTopnavsTeacherRoute
  '/dashboard/admin-staff/academic-periods': typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  '/dashboard/admin-staff/academic-years': typeof AuthedDashboardSidenavsAdminStaffAcademicYearsRoute
  '/dashboard/admin-staff/': typeof AuthedDashboardSidenavsAdminStaffIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/dashboard/principal': typeof AuthedDashboardTopnavsPrincipalRoute
  '/dashboard/student': typeof AuthedDashboardTopnavsStudentRoute
  '/dashboard/teacher': typeof AuthedDashboardTopnavsTeacherRoute
  '/dashboard/admin-staff/academic-periods': typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  '/dashboard/admin-staff/academic-years': typeof AuthedDashboardSidenavsAdminStaffAcademicYearsRoute
  '/dashboard/admin-staff': typeof AuthedDashboardSidenavsAdminStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_layout': typeof AuthedLayoutRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/dashboard/_sidenavs': typeof AuthedDashboardSidenavsRouteWithChildren
  '/_authed/dashboard/_topnavs': typeof AuthedDashboardTopnavsRouteWithChildren
  '/_authed/onboarding/academic-setup': typeof AuthedOnboardingAcademicSetupRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/_sidenavs/admin-staff': typeof AuthedDashboardSidenavsAdminStaffRouteWithChildren
  '/_authed/dashboard/_topnavs/principal': typeof AuthedDashboardTopnavsPrincipalRoute
  '/_authed/dashboard/_topnavs/student': typeof AuthedDashboardTopnavsStudentRoute
  '/_authed/dashboard/_topnavs/teacher': typeof AuthedDashboardTopnavsTeacherRoute
  '/_authed/dashboard/_sidenavs/admin-staff/academic-periods': typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  '/_authed/dashboard/_sidenavs/admin-staff/academic-years': typeof AuthedDashboardSidenavsAdminStaffAcademicYearsRoute
  '/_authed/dashboard/_sidenavs/admin-staff/': typeof AuthedDashboardSidenavsAdminStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/dashboard'
    | '/onboarding/academic-setup'
    | '/dashboard/admin-staff'
    | '/dashboard/principal'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/admin-staff/academic-periods'
    | '/dashboard/admin-staff/academic-years'
    | '/dashboard/admin-staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/dashboard'
    | '/onboarding/academic-setup'
    | '/dashboard/principal'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/admin-staff/academic-periods'
    | '/dashboard/admin-staff/academic-years'
    | '/dashboard/admin-staff'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/_layout'
    | '/auth/_layout'
    | '/auth/login'
    | '/auth/register'
    | '/_authed/'
    | '/_authed/dashboard/_sidenavs'
    | '/_authed/dashboard/_topnavs'
    | '/_authed/onboarding/academic-setup'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/_sidenavs/admin-staff'
    | '/_authed/dashboard/_topnavs/principal'
    | '/_authed/dashboard/_topnavs/student'
    | '/_authed/dashboard/_topnavs/teacher'
    | '/_authed/dashboard/_sidenavs/admin-staff/academic-periods'
    | '/_authed/dashboard/_sidenavs/admin-staff/academic-years'
    | '/_authed/dashboard/_sidenavs/admin-staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_layout': {
      id: '/_authed/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/academic-setup': {
      id: '/_authed/onboarding/academic-setup'
      path: '/onboarding/academic-setup'
      fullPath: '/onboarding/academic-setup'
      preLoaderRoute: typeof AuthedOnboardingAcademicSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/_topnavs': {
      id: '/_authed/dashboard/_topnavs'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardTopnavsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/_sidenavs': {
      id: '/_authed/dashboard/_sidenavs'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardSidenavsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/_topnavs/teacher': {
      id: '/_authed/dashboard/_topnavs/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof AuthedDashboardTopnavsTeacherRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_topnavs/student': {
      id: '/_authed/dashboard/_topnavs/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthedDashboardTopnavsStudentRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_topnavs/principal': {
      id: '/_authed/dashboard/_topnavs/principal'
      path: '/principal'
      fullPath: '/dashboard/principal'
      preLoaderRoute: typeof AuthedDashboardTopnavsPrincipalRouteImport
      parentRoute: typeof AuthedDashboardTopnavsRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff': {
      id: '/_authed/dashboard/_sidenavs/admin-staff'
      path: '/admin-staff'
      fullPath: '/dashboard/admin-staff'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffRouteImport
      parentRoute: typeof AuthedDashboardSidenavsRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/'
      path: '/'
      fullPath: '/dashboard/admin-staff/'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffIndexRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/academic-years': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/academic-years'
      path: '/academic-years'
      fullPath: '/dashboard/admin-staff/academic-years'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicYearsRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
    '/_authed/dashboard/_sidenavs/admin-staff/academic-periods': {
      id: '/_authed/dashboard/_sidenavs/admin-staff/academic-periods'
      path: '/academic-periods'
      fullPath: '/dashboard/admin-staff/academic-periods'
      preLoaderRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRouteImport
      parentRoute: typeof AuthedDashboardSidenavsAdminStaffRoute
    }
  }
}

interface AuthedDashboardSidenavsAdminStaffRouteChildren {
  AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute
  AuthedDashboardSidenavsAdminStaffAcademicYearsRoute: typeof AuthedDashboardSidenavsAdminStaffAcademicYearsRoute
  AuthedDashboardSidenavsAdminStaffIndexRoute: typeof AuthedDashboardSidenavsAdminStaffIndexRoute
}

const AuthedDashboardSidenavsAdminStaffRouteChildren: AuthedDashboardSidenavsAdminStaffRouteChildren =
  {
    AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute:
      AuthedDashboardSidenavsAdminStaffAcademicPeriodsRoute,
    AuthedDashboardSidenavsAdminStaffAcademicYearsRoute:
      AuthedDashboardSidenavsAdminStaffAcademicYearsRoute,
    AuthedDashboardSidenavsAdminStaffIndexRoute:
      AuthedDashboardSidenavsAdminStaffIndexRoute,
  }

const AuthedDashboardSidenavsAdminStaffRouteWithChildren =
  AuthedDashboardSidenavsAdminStaffRoute._addFileChildren(
    AuthedDashboardSidenavsAdminStaffRouteChildren,
  )

interface AuthedDashboardSidenavsRouteChildren {
  AuthedDashboardSidenavsAdminStaffRoute: typeof AuthedDashboardSidenavsAdminStaffRouteWithChildren
}

const AuthedDashboardSidenavsRouteChildren: AuthedDashboardSidenavsRouteChildren =
  {
    AuthedDashboardSidenavsAdminStaffRoute:
      AuthedDashboardSidenavsAdminStaffRouteWithChildren,
  }

const AuthedDashboardSidenavsRouteWithChildren =
  AuthedDashboardSidenavsRoute._addFileChildren(
    AuthedDashboardSidenavsRouteChildren,
  )

interface AuthedDashboardTopnavsRouteChildren {
  AuthedDashboardTopnavsPrincipalRoute: typeof AuthedDashboardTopnavsPrincipalRoute
  AuthedDashboardTopnavsStudentRoute: typeof AuthedDashboardTopnavsStudentRoute
  AuthedDashboardTopnavsTeacherRoute: typeof AuthedDashboardTopnavsTeacherRoute
}

const AuthedDashboardTopnavsRouteChildren: AuthedDashboardTopnavsRouteChildren =
  {
    AuthedDashboardTopnavsPrincipalRoute: AuthedDashboardTopnavsPrincipalRoute,
    AuthedDashboardTopnavsStudentRoute: AuthedDashboardTopnavsStudentRoute,
    AuthedDashboardTopnavsTeacherRoute: AuthedDashboardTopnavsTeacherRoute,
  }

const AuthedDashboardTopnavsRouteWithChildren =
  AuthedDashboardTopnavsRoute._addFileChildren(
    AuthedDashboardTopnavsRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedLayoutRoute: typeof AuthedLayoutRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDashboardSidenavsRoute: typeof AuthedDashboardSidenavsRouteWithChildren
  AuthedDashboardTopnavsRoute: typeof AuthedDashboardTopnavsRouteWithChildren
  AuthedOnboardingAcademicSetupRoute: typeof AuthedOnboardingAcademicSetupRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLayoutRoute: AuthedLayoutRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDashboardSidenavsRoute: AuthedDashboardSidenavsRouteWithChildren,
  AuthedDashboardTopnavsRoute: AuthedDashboardTopnavsRouteWithChildren,
  AuthedOnboardingAcademicSetupRoute: AuthedOnboardingAcademicSetupRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
